# Site settings
title: Julius Alexander IV
email: your-email@domain.com
  # I'm just trying to see as much of none of the Universe as I can.
description: > # this means to ignore newlines until "baseurl:"
  This site was built with Jekyll, an RPI education, and love.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: JAlexanderIV
github_username:  JuliusAlexanderIV

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:shorthand