# Site settings
title: Julius Alexander IV
email: your-email@domain.com
# > means to ignore newlines until "baseurl:"
description: >
  This site was built with Jekyll and foraged knowledge.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: JAlexanderIV
github_username:  JuliusAlexanderIV

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:shorthand