# Site settings
title: Julius Alexander IV
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here's some placeholder text for words that will eventually end up here.
  What will those words be? Well I'd like to say clever but I've been wrong
  before.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: JAlexanderIV
github_username:  JuliusAlexanderIV

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:title